name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install package
        run: |
          pip install --upgrade pip

      - name: Linting with flake8
        run: |
          pip install flake8
          flake8 --show-source --ignore=F401
      - name: Unit tests with pytest
        run: |
          pip install pytest
          pytest -v      



